USE [master]
GO
/****** Object:  Database [FLEX]    Script Date: 13/05/2023 12:03:53 AM ******/
CREATE DATABASE [FLEX]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FLEX', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS02\MSSQL\DATA\FLEX.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FLEX_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS02\MSSQL\DATA\FLEX_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [FLEX] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FLEX].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [FLEX] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [FLEX] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [FLEX] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [FLEX] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [FLEX] SET ARITHABORT OFF 
GO
ALTER DATABASE [FLEX] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [FLEX] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [FLEX] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [FLEX] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [FLEX] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [FLEX] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [FLEX] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [FLEX] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [FLEX] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [FLEX] SET  ENABLE_BROKER 
GO
ALTER DATABASE [FLEX] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [FLEX] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [FLEX] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [FLEX] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [FLEX] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [FLEX] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [FLEX] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [FLEX] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [FLEX] SET  MULTI_USER 
GO
ALTER DATABASE [FLEX] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [FLEX] SET DB_CHAINING OFF 
GO
ALTER DATABASE [FLEX] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [FLEX] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [FLEX] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [FLEX] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [FLEX] SET QUERY_STORE = ON
GO
ALTER DATABASE [FLEX] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [FLEX]
GO
/****** Object:  Table [dbo].[ACADEMICS]    Script Date: 13/05/2023 12:03:53 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACADEMICS](
	[ACD_ID] [int] NOT NULL,
	[USERID] [int] NULL,
	[F_NAME] [varchar](50) NOT NULL,
	[L_NAME] [varchar](50) NULL,
	[ACAD_NAME]  AS (concat([F_NAME],' ',[L_NAME])),
	[ACAD_LOC] [varchar](10) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ACD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ATTENDANCE]    Script Date: 13/05/2023 12:03:53 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ATTENDANCE](
	[REG_NUM] [int] NOT NULL,
	[DATE_TIME] [datetime] NOT NULL,
	[A_STATUS] [varchar](10) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[REG_NUM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[COORDINATORS]    Script Date: 13/05/2023 12:03:53 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COORDINATORS](
	[COD] [int] NOT NULL,
	[FAC_ID] [int] NULL,
	[COURSE_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[COD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[COURSES]    Script Date: 13/05/2023 12:03:53 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COURSES](
	[COURSE_ID] [int] IDENTITY(1,1) NOT NULL,
	[COURSE_CODE] [varchar](10) NOT NULL,
	[COURSE_NAME] [varchar](50) NOT NULL,
	[CRED_HRS] [float] NOT NULL,
	[PRE_REQ_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[COURSE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[COURSE_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EVALUATION]    Script Date: 13/05/2023 12:03:53 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EVALUATION](
	[SECTION_ID] [int] NOT NULL,
	[COURSE_ID] [int] NOT NULL,
	[WEIGHTAGE] [float] NULL,
	[E_TYPE] [varchar](20) NULL,
	[E_STATUS] [varchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[SECTION_ID] ASC,
	[COURSE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FACULTY]    Script Date: 13/05/2023 12:03:53 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FACULTY](
	[USERID] [int] NULL,
	[FACULTY_ID] [int] NOT NULL,
	[F_NAME] [varchar](50) NOT NULL,
	[L_NAME] [varchar](50) NULL,
	[FACULTY_NAME]  AS (concat([F_NAME],' ',[L_NAME])),
PRIMARY KEY CLUSTERED 
(
	[FACULTY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FEEDBACK]    Script Date: 13/05/2023 12:03:53 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FEEDBACK](
	[FAC_ID] [int] NOT NULL,
	[REG_NUM] [int] NOT NULL,
	[COURSE_ID] [int] NOT NULL,
	[COMMENT] [varchar](1000) NULL,
PRIMARY KEY CLUSTERED 
(
	[FAC_ID] ASC,
	[REG_NUM] ASC,
	[COURSE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MARKS]    Script Date: 13/05/2023 12:03:53 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MARKS](
	[REG_NUM] [int] NOT NULL,
	[COURSE_ID] [int] NOT NULL,
	[MARKS] [float] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[REG_NUM] ASC,
	[COURSE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[REGISTRATION]    Script Date: 13/05/2023 12:03:53 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REGISTRATION](
	[ID] [int] NOT NULL,
	[SECTION_ID] [int] NULL,
	[REG_NUM] [int] NULL,
	[REG_YEAR] [varchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SECTIONS]    Script Date: 13/05/2023 12:03:53 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SECTIONS](
	[SECTION_ID] [int] NOT NULL,
	[CAPACITY] [int] NOT NULL,
	[SECTION_NUM] [int] NOT NULL,
	[OFFERED_COURSES_ID] [int] NOT NULL,
	[FACULTY_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SECTION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[STUDENTS]    Script Date: 13/05/2023 12:03:53 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[STUDENTS](
	[USERID] [int] NOT NULL,
	[REG_NUM] [int] NOT NULL,
	[CNIC] [char](14) NOT NULL,
	[PHONE_NUM] [varchar](11) NOT NULL,
	[F_NAME] [varchar](50) NOT NULL,
	[L_NAME] [varchar](50) NULL,
	[STUDENT_NAME]  AS (concat([F_NAME],' ',[L_NAME])),
	[BLOOD_GROUP] [varchar](3) NOT NULL,
	[HOUSE_NO] [varchar](10) NULL,
	[STREET_NO] [varchar](20) NULL,
	[LOC_AREA] [varchar](20) NULL,
	[PROG_NAME] [varchar](10) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[REG_NUM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[REG_NUM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USERS]    Script Date: 13/05/2023 12:03:53 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USERS](
	[USERID] [int] NOT NULL,
	[USERNAME] [varchar](50) NULL,
	[USER_PASSWORD] [varchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[USERID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[USERNAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACADEMICS]  WITH CHECK ADD FOREIGN KEY([USERID])
REFERENCES [dbo].[USERS] ([USERID])
GO
ALTER TABLE [dbo].[ATTENDANCE]  WITH CHECK ADD FOREIGN KEY([REG_NUM])
REFERENCES [dbo].[STUDENTS] ([REG_NUM])
GO
ALTER TABLE [dbo].[COORDINATORS]  WITH CHECK ADD FOREIGN KEY([COURSE_ID])
REFERENCES [dbo].[COURSES] ([COURSE_ID])
GO
ALTER TABLE [dbo].[COORDINATORS]  WITH CHECK ADD FOREIGN KEY([FAC_ID])
REFERENCES [dbo].[FACULTY] ([FACULTY_ID])
GO
ALTER TABLE [dbo].[COURSES]  WITH CHECK ADD FOREIGN KEY([PRE_REQ_ID])
REFERENCES [dbo].[COURSES] ([COURSE_ID])
GO
ALTER TABLE [dbo].[EVALUATION]  WITH CHECK ADD FOREIGN KEY([COURSE_ID])
REFERENCES [dbo].[COURSES] ([COURSE_ID])
GO
ALTER TABLE [dbo].[EVALUATION]  WITH CHECK ADD FOREIGN KEY([SECTION_ID])
REFERENCES [dbo].[SECTIONS] ([SECTION_ID])
GO
ALTER TABLE [dbo].[FACULTY]  WITH CHECK ADD FOREIGN KEY([USERID])
REFERENCES [dbo].[USERS] ([USERID])
GO
ALTER TABLE [dbo].[FEEDBACK]  WITH CHECK ADD FOREIGN KEY([COURSE_ID])
REFERENCES [dbo].[COURSES] ([COURSE_ID])
GO
ALTER TABLE [dbo].[FEEDBACK]  WITH CHECK ADD FOREIGN KEY([FAC_ID])
REFERENCES [dbo].[FACULTY] ([FACULTY_ID])
GO
ALTER TABLE [dbo].[FEEDBACK]  WITH CHECK ADD FOREIGN KEY([REG_NUM])
REFERENCES [dbo].[STUDENTS] ([REG_NUM])
GO
ALTER TABLE [dbo].[MARKS]  WITH CHECK ADD FOREIGN KEY([COURSE_ID])
REFERENCES [dbo].[COURSES] ([COURSE_ID])
GO
ALTER TABLE [dbo].[MARKS]  WITH CHECK ADD FOREIGN KEY([REG_NUM])
REFERENCES [dbo].[STUDENTS] ([REG_NUM])
GO
ALTER TABLE [dbo].[REGISTRATION]  WITH CHECK ADD FOREIGN KEY([REG_NUM])
REFERENCES [dbo].[STUDENTS] ([REG_NUM])
GO
ALTER TABLE [dbo].[REGISTRATION]  WITH CHECK ADD FOREIGN KEY([SECTION_ID])
REFERENCES [dbo].[SECTIONS] ([SECTION_ID])
GO
ALTER TABLE [dbo].[SECTIONS]  WITH CHECK ADD FOREIGN KEY([FACULTY_ID])
REFERENCES [dbo].[FACULTY] ([FACULTY_ID])
GO
ALTER TABLE [dbo].[SECTIONS]  WITH CHECK ADD FOREIGN KEY([OFFERED_COURSES_ID])
REFERENCES [dbo].[COURSES] ([COURSE_ID])
GO
ALTER TABLE [dbo].[STUDENTS]  WITH CHECK ADD FOREIGN KEY([USERID])
REFERENCES [dbo].[USERS] ([USERID])
GO
ALTER TABLE [dbo].[ATTENDANCE]  WITH CHECK ADD CHECK  (([A_STATUS] like '%PRESENT%' OR [A_STATUS] like '%Present%' OR [A_STATUS] like '%LATE%' OR [A_STATUS] like '%Late%' OR [A_STATUS] like '%ABSENT%' OR [A_STATUS] like '%Absent%'))
GO
ALTER TABLE [dbo].[STUDENTS]  WITH CHECK ADD CHECK  (([BLOOD_GROUP]='AB-' OR [BLOOD_GROUP]='AB+' OR [BLOOD_GROUP]='O-' OR [BLOOD_GROUP]='O+' OR [BLOOD_GROUP]='B-' OR [BLOOD_GROUP]='B+' OR [BLOOD_GROUP]='A-' OR [BLOOD_GROUP]='A+'))
GO
ALTER TABLE [dbo].[STUDENTS]  WITH CHECK ADD CHECK  (([CNIC] like '[0-9][0-9][0-9][0-9]-[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'))
GO
ALTER TABLE [dbo].[USERS]  WITH CHECK ADD CHECK  ((len([USER_PASSWORD])>=(8) AND [USER_PASSWORD] like '%[a-z]%' AND [USER_PASSWORD] like '%[A-Z]%' AND [USER_PASSWORD] like '%[0-9]%'))
GO
USE [master]
GO
ALTER DATABASE [FLEX] SET  READ_WRITE 
GO
